import type { Config, ConfigSection } from '../../shared/config';
import { OPTIONS } from '../../shared/enums';
export const PANELS = [
  'General',
  'Sprites',
  'Model',
  'Persona',
  'Voice',
  'Voice Input',
  'Appearance',
  'Advanced',
] as const;
export type Panel = (typeof PANELS)[number];
export type Setting = {
  id: number;
  panel: Panel;
  group: string;
  section: ConfigSection;
  key: string;
  label: string;
  kind:
    | 'toggle'
    | 'select'
    | 'number'
    | 'range'
    | 'text'
    | 'textarea'
    | 'color'
    | 'tags'
    | 'model'
    | 'font';
  options?: readonly (readonly [string, string])[];
  min?: number;
  max?: number;
  step?: number;
  multiplier?: number;
  reverse?: boolean;
  suffix?: string;
  hint?: string;
  synonyms?: string;
  restart?: boolean;
  rows?: number;
  maxLength?: number;
  placeholder?: string;
  visible?: (cfg: Config) => boolean;
  disabled?: (cfg: Config) => boolean;
  disabledHint?: string;
  unavailableOptions?: readonly string[];
};
const field = <S extends ConfigSection>(
  section: S,
  key: keyof Config[S] & string,
  definition: Omit<Setting, 'section' | 'key'>,
): Setting => ({ ...definition, section, key });
const general = (
  key: keyof Config['window'],
  definition: Omit<Setting, 'section' | 'key' | 'panel'>,
) => field('window', key, { ...definition, panel: 'General' });
const model = (key: keyof Config['llm'], definition: Omit<Setting, 'section' | 'key' | 'panel'>) =>
  field('llm', key, { ...definition, panel: 'Model' });
const bubble = (
  key: keyof Config['bubble'],
  definition: Omit<Setting, 'section' | 'key' | 'panel'>,
) => field('bubble', key, { ...definition, panel: 'Appearance' });
const input = (
  key: keyof Config['input'],
  definition: Omit<Setting, 'section' | 'key' | 'panel'>,
) => field('input', key, { ...definition, panel: 'Appearance' });
const notMock = (cfg: Config) => cfg.llm.provider !== 'mock';
const speech = (cfg: Config) => cfg.tts.provider !== 'none';
const voice = (
  key:
    | keyof Config['tts']
    | `elevenlabs.${keyof Config['tts']['elevenlabs']}`
    | `custom.${keyof Config['tts']['custom']}`,
  definition: Omit<Setting, 'section' | 'key' | 'panel'>,
): Setting => ({ ...definition, section: 'tts', key, panel: 'Voice' });
const eleven = (cfg: Config) => cfg.tts.provider === 'elevenlabs';
const customVoice = (cfg: Config) => cfg.tts.provider === 'custom-http';
const enabledStt = (cfg: Config) => cfg.stt.provider !== 'none';
const httpStt = (cfg: Config) => cfg.stt.provider === 'openai-compatible-stt';
const advanced = (
  key: keyof Config['advanced'],
  definition: Omit<Setting, 'section' | 'key' | 'panel'>,
) => field('advanced', key, { ...definition, panel: 'Advanced' });
const stt = (key: keyof Config['stt'], definition: Omit<Setting, 'section' | 'key' | 'panel'>) =>
  field('stt', key, { ...definition, panel: 'Voice Input' });
export const SETTINGS: Setting[] = [
  advanced('clickThrough', {
    id: 156,
    group: 'Interaction',
    label: 'Click-through mode',
    kind: 'select',
    options: OPTIONS.clickThrough,
  }),
  advanced('alphaThreshold', {
    id: 157,
    group: 'Interaction',
    label: 'Transparency threshold',
    kind: 'range',
    min: 1,
    max: 254,
    visible: (cfg) => cfg.advanced.clickThrough === 'alpha-mask',
    hint: 'Pixels with alpha below this value let clicks pass through to whatever is behind the companion.',
  }),
  advanced('hitTestEveryNFrames', {
    id: 158,
    group: 'Interaction',
    label: 'Hit-test sample rate',
    kind: 'select',
    options: OPTIONS.hitTestEveryNFrames,
    visible: (cfg) => cfg.advanced.clickThrough === 'alpha-mask',
  }),
  advanced('dragEnabled', {
    id: 159,
    group: 'Interaction',
    label: 'Allow dragging the sprite',
    kind: 'toggle',
  }),
  advanced('dragModifier', {
    id: 160,
    group: 'Interaction',
    label: 'Drag requires modifier key',
    kind: 'select',
    options: OPTIONS.dragModifier,
    visible: (cfg) => cfg.advanced.dragEnabled,
  }),
  advanced('fpsCap', {
    id: 161,
    group: 'Performance',
    label: 'Animation frame rate cap',
    kind: 'select',
    options: OPTIONS.fpsCap,
  }),
  advanced('pauseWhenHidden', {
    id: 162,
    group: 'Performance',
    label: 'Pause animation when sprite is not visible',
    kind: 'toggle',
  }),
  advanced('reduceOnBattery', {
    id: 163,
    group: 'Performance',
    label: 'Reduce frame rate on battery power',
    kind: 'toggle',
  }),
  advanced('hardwareAcceleration', {
    id: 164,
    group: 'Performance',
    label: 'Hardware acceleration',
    kind: 'toggle',
    restart: true,
  }),
  advanced('spriteCacheMb', {
    id: 165,
    group: 'Performance',
    label: 'Sprite cache size',
    kind: 'select',
    options: OPTIONS.spriteCacheMb,
  }),
  advanced('proxyMode', {
    id: 166,
    group: 'Network',
    label: 'Proxy',
    kind: 'select',
    options: OPTIONS.proxyMode,
  }),
  advanced('proxyUrl', {
    id: 167,
    group: 'Network',
    label: 'Proxy URL',
    kind: 'text',
    maxLength: 2000,
    placeholder: 'http://host:port or socks5://host:port',
    visible: (cfg) => cfg.advanced.proxyMode === 'manual',
    hint: 'Enter a proxy URL to enable manual routing. An empty URL uses a direct connection.',
  }),
  advanced('proxyBypass', {
    id: 168,
    group: 'Network',
    label: 'Bypass proxy for',
    kind: 'text',
    maxLength: 2000,
    visible: (cfg) => cfg.advanced.proxyMode === 'manual',
    hint: 'localhost, 127.0.0.1 recommended for local models',
  }),
  advanced('allowSelfSigned', {
    id: 169,
    group: 'Network',
    label: '⚠ Allow self-signed certificates',
    kind: 'toggle',
    hint: 'Only enable this for local endpoints you control.',
  }),
  advanced('logLevel', {
    id: 170,
    group: 'Data & Diagnostics',
    label: 'Log level',
    kind: 'select',
    options: OPTIONS.logLevel,
  }),
  advanced('redactPrompts', {
    id: 171,
    group: 'Data & Diagnostics',
    label: 'Redact prompts and replies from logs',
    kind: 'toggle',
  }),
  advanced('developerMode', {
    id: 178,
    group: 'Developer',
    label: 'Developer mode',
    kind: 'toggle',
  }),
  stt('provider', {
    id: 187,
    group: 'Provider',
    label: 'Speech-to-text provider',
    kind: 'select',
    options: OPTIONS.sttProvider,
    unavailableOptions: ['windows-dictation', 'whisper-local', 'custom-http'],
  }),
  stt('baseUrl', {
    id: 190,
    group: 'OpenAI-compatible endpoint (Whisper)',
    label: 'Base URL',
    kind: 'text',
    visible: httpStt,
    maxLength: 2000,
    hint: 'A local Whisper container typically runs at http://localhost:9000/v1. faster-whisper-server and LocalAI also use this shape.',
  }),
  stt('model', {
    id: 192,
    group: 'OpenAI-compatible endpoint (Whisper)',
    label: 'Model',
    kind: 'model',
    visible: httpStt,
    maxLength: 200,
  }),
  stt('activation', {
    id: 208,
    group: 'Activation',
    label: 'How voice input starts',
    kind: 'select',
    options: OPTIONS.activation,
    visible: enabledStt,
    unavailableOptions: ['push-to-talk', 'hands-free'],
    hint: 'The microphone button toggles recording. Global push-to-talk and hands-free activation arrive in the next phase.',
  }),
  stt('showMicButton', {
    id: 209,
    group: 'Activation',
    label: 'Show a microphone button on the input box',
    kind: 'toggle',
    visible: enabledStt,
  }),
  stt('silenceTimeoutMs', {
    id: 210,
    group: 'Activation',
    label: 'Stop listening after silence',
    kind: 'range',
    min: 0.3,
    max: 5,
    step: 0.1,
    multiplier: 1000,
    suffix: 's',
    visible: (cfg) => enabledStt(cfg) && cfg.stt.activation !== 'push-to-talk',
  }),
  stt('maxUtteranceSec', {
    id: 211,
    group: 'Activation',
    label: 'Maximum recording length',
    kind: 'range',
    min: 5,
    max: 300,
    suffix: 's',
    visible: enabledStt,
    hint: 'A safety watchdog stops every recording after 120 seconds, even when a longer length is selected.',
  }),
  stt('startSound', {
    id: 212,
    group: 'Activation',
    label: 'Play a sound when recording starts / stops',
    kind: 'toggle',
    visible: enabledStt,
  }),
  stt('pauseWhileSpeaking', {
    id: 213,
    group: 'Activation',
    label: 'Pause listening while the companion is speaking',
    kind: 'toggle',
    visible: (cfg) => enabledStt(cfg) && cfg.tts.provider !== 'none',
  }),
  stt('inputDeviceId', {
    id: 214,
    group: 'Input Device',
    label: 'Microphone',
    kind: 'select',
    visible: enabledStt,
  }),
  stt('inputGain', {
    id: 216,
    group: 'Input Device',
    label: 'Input gain',
    kind: 'range',
    min: 0.5,
    max: 4,
    step: 0.1,
    suffix: '×',
    visible: enabledStt,
  }),
  stt('noiseSuppression', {
    id: 217,
    group: 'Input Device',
    label: 'Noise suppression',
    kind: 'select',
    options: OPTIONS.noiseSuppression,
    visible: enabledStt,
  }),
  stt('echoCancellation', {
    id: 218,
    group: 'Input Device',
    label: 'Echo cancellation',
    kind: 'toggle',
    visible: enabledStt,
  }),
  stt('vadThreshold', {
    id: 219,
    group: 'Input Device',
    label: 'Voice detection sensitivity',
    kind: 'range',
    min: 0.005,
    max: 0.08,
    step: 0.001,
    reverse: true,
    visible: (cfg) => enabledStt(cfg) && cfg.stt.activation !== 'push-to-talk',
    hint: 'Low → High. Higher sensitivity detects quieter speech.',
  }),
  stt('language', {
    id: 221,
    group: 'Transcription Handling',
    label: 'Spoken language',
    kind: 'select',
    options: [
      ['auto', 'Detect automatically'],
      ['en', 'English'],
      ['es', 'Spanish'],
      ['ja', 'Japanese'],
      ['fr', 'French'],
      ['de', 'German'],
      ['it', 'Italian'],
      ['pt', 'Portuguese'],
      ['zh', 'Chinese'],
      ['ko', 'Korean'],
      ['ru', 'Russian'],
      ['ar', 'Arabic'],
      ['hi', 'Hindi'],
    ],
    visible: enabledStt,
  }),
  stt('transcriptAction', {
    id: 222,
    group: 'Transcription Handling',
    label: 'What to do with the transcript',
    kind: 'select',
    options: OPTIONS.transcriptAction,
    visible: enabledStt,
  }),
  stt('countdownMs', {
    id: 223,
    group: 'Transcription Handling',
    label: 'Countdown before sending',
    kind: 'range',
    min: 0.5,
    max: 5,
    step: 0.5,
    multiplier: 1000,
    suffix: 's',
    visible: (cfg) => enabledStt(cfg) && cfg.stt.transcriptAction === 'countdown',
  }),
  stt('showPartials', {
    id: 224,
    group: 'Transcription Handling',
    label: 'Show words as I speak',
    kind: 'toggle',
    disabled: (cfg) => cfg.stt.provider !== 'windows-dictation',
    disabledHint: 'This provider returns the full transcript at once.',
    visible: enabledStt,
  }),
  stt('insertMode', {
    id: 225,
    group: 'Transcription Handling',
    label: 'Insert transcript',
    kind: 'select',
    options: OPTIONS.insertMode,
    visible: enabledStt,
  }),
  stt('autoCapitalize', {
    id: 226,
    group: 'Transcription Handling',
    label: 'Capitalize and punctuate',
    kind: 'toggle',
    visible: enabledStt,
  }),
  stt('spokenPunctuation', {
    id: 227,
    group: 'Transcription Handling',
    label: 'Recognize spoken punctuation',
    kind: 'toggle',
    visible: enabledStt,
    hint: 'Turns spoken words such as “period”, “comma” and “new line” into characters. Most Whisper models already punctuate.',
  }),
  stt('trimFillers', {
    id: 228,
    group: 'Transcription Handling',
    label: 'Remove filler words',
    kind: 'toggle',
    visible: enabledStt,
  }),
  stt('prompt', {
    id: 229,
    group: 'Transcription Handling',
    label: 'Custom vocabulary',
    kind: 'textarea',
    rows: 3,
    maxLength: 1000,
    hint: 'Helps the engine recognize unusual names, jargon, and acronyms.',
    visible: enabledStt,
  }),
  stt('minConfidence', {
    id: 230,
    group: 'Transcription Handling',
    label: 'Discard transcripts below confidence',
    kind: 'range',
    min: 0,
    max: 90,
    multiplier: 0.01,
    suffix: '%',
    hint: 'Not all engines report confidence. When unavailable, every transcript is kept.',
    visible: enabledStt,
  }),
  stt('onFailure', {
    id: 231,
    group: 'Transcription Handling',
    label: 'If transcription fails',
    kind: 'select',
    options: OPTIONS.sttFailure,
    unavailableOptions: ['sapi-dictation'],
    visible: enabledStt,
  }),
  stt('includeTranscriptsInLogs', {
    id: 232,
    group: 'Privacy',
    label: 'Include transcripts in logs',
    kind: 'toggle',
    disabled: (cfg) => cfg.advanced.redactPrompts,
    disabledHint: 'Disabled because log redaction is enabled in Advanced.',
    visible: enabledStt,
  }),
  voice('provider', {
    id: 83,
    group: 'Provider',
    label: 'Text-to-speech provider',
    kind: 'select',
    options: OPTIONS.ttsProvider,
  }),
  voice('voice', {
    id: 84,
    group: 'Windows built-in (SAPI)',
    label: 'Voice',
    kind: 'select',
    visible: (cfg) => cfg.tts.provider === 'windows-sapi',
  }),
  voice('pitch', {
    id: 85,
    group: 'Windows built-in (SAPI)',
    label: 'Pitch',
    kind: 'range',
    min: -10,
    max: 10,
    visible: (cfg) => cfg.tts.provider === 'windows-sapi',
  }),
  voice('baseUrl', {
    id: 86,
    group: 'OpenAI-compatible endpoint',
    label: 'Base URL',
    kind: 'text',
    maxLength: 2000,
    visible: (cfg) => cfg.tts.provider === 'openai-compatible-tts',
    hint: 'Kokoro-FastAPI in Docker typically runs at http://localhost:8880/v1. LocalAI uses http://localhost:8080/v1. A local Kokoro endpoint needs no API key or account and can run offline.',
  }),
  voice('model', {
    id: 88,
    group: 'OpenAI-compatible endpoint',
    label: 'Model',
    kind: 'model',
    maxLength: 200,
    visible: (cfg) => cfg.tts.provider === 'openai-compatible-tts',
  }),
  voice('voice', {
    id: 89,
    group: 'OpenAI-compatible endpoint',
    label: 'Voice',
    kind: 'model',
    maxLength: 200,
    visible: (cfg) => cfg.tts.provider === 'openai-compatible-tts',
  }),
  voice('format', {
    id: 90,
    group: 'OpenAI-compatible endpoint',
    label: 'Audio format',
    kind: 'select',
    options: OPTIONS.audioFormat,
    visible: (cfg) => cfg.tts.provider === 'openai-compatible-tts',
  }),
  voice('elevenlabs.voiceId', {
    id: 92,
    group: 'ElevenLabs',
    label: 'Voice',
    kind: 'select',
    visible: eleven,
  }),
  voice('elevenlabs.modelId', {
    id: 93,
    group: 'ElevenLabs',
    label: 'Model',
    kind: 'select',
    options: OPTIONS.elevenModel,
    visible: eleven,
  }),
  voice('elevenlabs.stability', {
    id: 94,
    group: 'ElevenLabs',
    label: 'Stability',
    kind: 'range',
    min: 0,
    max: 1,
    step: 0.01,
    visible: eleven,
  }),
  voice('elevenlabs.similarityBoost', {
    id: 95,
    group: 'ElevenLabs',
    label: 'Similarity boost',
    kind: 'range',
    min: 0,
    max: 1,
    step: 0.01,
    visible: eleven,
  }),
  voice('elevenlabs.style', {
    id: 96,
    group: 'ElevenLabs',
    label: 'Style exaggeration',
    kind: 'range',
    min: 0,
    max: 1,
    step: 0.01,
    visible: eleven,
  }),
  voice('elevenlabs.speakerBoost', {
    id: 97,
    group: 'ElevenLabs',
    label: 'Speaker boost',
    kind: 'toggle',
    visible: eleven,
  }),
  voice('custom.url', {
    id: 98,
    group: 'Custom HTTP endpoint',
    label: 'Request URL',
    kind: 'text',
    maxLength: 2000,
    visible: customVoice,
  }),
  voice('custom.method', {
    id: 99,
    group: 'Custom HTTP endpoint',
    label: 'HTTP method',
    kind: 'select',
    options: OPTIONS.ttsMethod,
    visible: customVoice,
  }),
  voice('custom.bodyTemplate', {
    id: 102,
    group: 'Custom HTTP endpoint',
    label: 'Body template',
    kind: 'textarea',
    rows: 4,
    maxLength: 16000,
    hint: 'JSON containing {{text}}; also supports {{voice}} and {{speed}}. GET sends these fields as query parameters.',
    visible: customVoice,
  }),
  voice('custom.responseMode', {
    id: 103,
    group: 'Custom HTTP endpoint',
    label: 'Response type',
    kind: 'select',
    options: OPTIONS.responseMode,
    visible: customVoice,
  }),
  voice('custom.jsonPath', {
    id: 104,
    group: 'Custom HTTP endpoint',
    label: 'JSON field path',
    kind: 'text',
    maxLength: 200,
    hint: 'For example: data.audio. Numeric path segments select array entries.',
    visible: (cfg) => customVoice(cfg) && cfg.tts.custom.responseMode !== 'binary',
  }),
  voice('custom.format', {
    id: 105,
    group: 'Custom HTTP endpoint',
    label: 'Audio format',
    kind: 'select',
    options: OPTIONS.customAudioFormat,
    visible: customVoice,
  }),
  voice('outputDeviceId', {
    id: 106,
    group: 'Playback',
    label: 'Output device',
    kind: 'select',
    visible: speech,
  }),
  voice('volume', {
    id: 107,
    group: 'Playback',
    label: 'Volume',
    kind: 'range',
    min: 0,
    max: 100,
    multiplier: 0.01,
    suffix: '%',
    visible: speech,
  }),
  voice('speed', {
    id: 108,
    group: 'Playback',
    label: 'Speaking rate',
    kind: 'range',
    min: 0.5,
    max: 2,
    step: 0.05,
    visible: speech,
  }),
  voice('beginSpeaking', {
    id: 109,
    group: 'Playback',
    label: 'Begin speaking',
    kind: 'select',
    options: OPTIONS.beginSpeaking,
    visible: speech,
  }),
  voice('onNewMessage', {
    id: 110,
    group: 'Playback',
    label: 'If I send a new message while speaking',
    kind: 'select',
    options: OPTIONS.onNewMessage,
    visible: speech,
  }),
  voice('codeBlockSpeech', {
    id: 112,
    group: 'Text Processing',
    label: 'Code blocks',
    kind: 'select',
    options: OPTIONS.codeBlockSpeech,
    visible: speech,
  }),
  voice('linkSpeech', {
    id: 113,
    group: 'Text Processing',
    label: 'Links',
    kind: 'select',
    options: OPTIONS.linkSpeech,
    visible: speech,
  }),
  voice('emojiSpeech', {
    id: 114,
    group: 'Text Processing',
    label: 'Emoji',
    kind: 'select',
    options: OPTIONS.emojiSpeech,
    visible: speech,
  }),
  voice('maxSpeechChars', {
    id: 115,
    group: 'Text Processing',
    label: 'Max characters to speak',
    kind: 'number',
    min: 100,
    max: 20000,
    visible: speech,
    hint: 'Longer replies are truncated for speech only. The full text always appears in the bubble.',
  }),
  voice('cacheAudio', {
    id: 116,
    group: 'Text Processing',
    label: 'Cache synthesized audio',
    kind: 'toggle',
    visible: speech,
  }),
  voice('onFailure', {
    id: 117,
    group: 'Text Processing',
    label: 'If speech fails',
    kind: 'select',
    options: OPTIONS.ttsFailure,
    visible: speech,
  }),
  field('sprite', 'scale', {
    id: 37,
    panel: 'Sprites',
    group: 'Global Sprite Settings',
    label: 'Sprite scale',
    kind: 'range',
    min: 25,
    max: 400,
    step: 5,
    multiplier: 0.01,
    suffix: '%',
  }),
  field('sprite', 'scaleMode', {
    id: 38,
    panel: 'Sprites',
    group: 'Global Sprite Settings',
    label: 'Scale mode',
    kind: 'select',
    options: OPTIONS.scaleMode,
  }),
  field('sprite', 'flipHorizontal', {
    id: 39,
    panel: 'Sprites',
    group: 'Global Sprite Settings',
    label: 'Flip horizontally',
    kind: 'toggle',
  }),
  field('sprite', 'pixelated', {
    id: 40,
    panel: 'Sprites',
    group: 'Global Sprite Settings',
    label: 'Image smoothing',
    kind: 'select',
    options: OPTIONS.pixelated,
  }),
  field('sprite', 'opacity', {
    id: 41,
    panel: 'Sprites',
    group: 'Global Sprite Settings',
    label: 'Sprite opacity',
    kind: 'range',
    min: 20,
    max: 100,
    multiplier: 0.01,
    suffix: '%',
  }),
  field('sprite', 'transition', {
    id: 42,
    panel: 'Sprites',
    group: 'Global Sprite Settings',
    label: 'State transition',
    kind: 'select',
    options: OPTIONS.transition,
  }),
  field('sprite', 'crossfadeMs', {
    id: 43,
    panel: 'Sprites',
    group: 'Global Sprite Settings',
    label: 'Crossfade duration',
    kind: 'range',
    min: 40,
    max: 500,
    suffix: 'ms',
    visible: (cfg) => cfg.sprite.transition === 'crossfade',
  }),
  field('sprite', 'minThinkingMs', {
    id: 44,
    panel: 'Sprites',
    group: 'Global Sprite Settings',
    label: 'Minimum thinking duration',
    kind: 'range',
    min: 0,
    max: 2000,
    suffix: 'ms',
    hint: 'Prevents a visible flicker when the model replies almost instantly.',
  }),
  general('launchAtLogin', {
    id: 1,
    group: 'Startup',
    label: 'Launch at Windows login',
    kind: 'toggle',
    synonyms: 'startup boot autostart',
  }),
  general('startMinimized', {
    id: 2,
    group: 'Startup',
    label: 'Start minimized (sprite hidden)',
    kind: 'toggle',
    disabled: (cfg) => !cfg.window.launchAtLogin,
  }),
  general('showInTaskbar', { id: 3, group: 'Startup', label: 'Show in taskbar', kind: 'toggle' }),
  general('restorePosition', {
    id: 4,
    group: 'Startup',
    label: 'Restore sprite position on launch',
    kind: 'toggle',
  }),
  general('onClose', {
    id: 5,
    group: 'Window Behavior',
    label: 'When the window is closed',
    kind: 'select',
    options: OPTIONS.onClose,
  }),
  general('fullscreenBehavior', {
    id: 6,
    group: 'Window Behavior',
    label: 'Hide sprite when a fullscreen app is active',
    kind: 'select',
    options: OPTIONS.fullscreenBehavior,
    synonyms: 'games gaming',
  }),
  general('allWorkspaces', {
    id: 7,
    group: 'Window Behavior',
    label: 'Show on all virtual desktops',
    kind: 'toggle',
    disabled: () => true,
    disabledHint:
      'Automatic pinning is deferred. Use Windows Task View to show the companion on all desktops.',
    hint: 'Automatic pinning is deferred. Enable Show in taskbar, press Win+Tab, right-click LittleLLM and choose Show this window on all desktops.',
  }),
  general('contentProtection', {
    id: 8,
    group: 'Window Behavior',
    label: 'Hide sprite from screen capture',
    kind: 'toggle',
    restart: true,
    hint: 'Prevents the sprite from appearing in screen shares and recordings. Some capture tools may ignore this.',
  }),
  general('displayTarget', {
    id: 9,
    group: 'Placement',
    label: 'Display',
    kind: 'select',
    options: OPTIONS.displayTarget,
    synonyms: 'monitor screen',
  }),
  general('defaultAnchor', {
    id: 10,
    group: 'Placement',
    label: 'Default anchor',
    kind: 'select',
    options: OPTIONS.defaultAnchor,
    hint: 'Used when restoring the sprite position is off.',
  }),
  general('edgeMarginPx', {
    id: 11,
    group: 'Placement',
    label: 'Edge margin',
    kind: 'range',
    min: 0,
    max: 200,
    step: 4,
    suffix: 'px',
  }),
  general('snapToEdges', {
    id: 12,
    group: 'Placement',
    label: 'Snap to screen edges',
    kind: 'toggle',
  }),
  general('snapDistancePx', {
    id: 13,
    group: 'Placement',
    label: 'Snap distance',
    kind: 'range',
    min: 4,
    max: 64,
    suffix: 'px',
  }),
  general('keepOnScreen', {
    id: 14,
    group: 'Placement',
    label: 'Keep fully on screen',
    kind: 'toggle',
  }),
  model('provider', {
    id: 60,
    group: 'Provider',
    label: 'Provider',
    kind: 'select',
    options: OPTIONS.llmProvider,
  }),
  model('baseUrl', {
    id: 61,
    group: 'Provider',
    label: 'Base URL',
    kind: 'text',
    maxLength: 2000,
    visible: notMock,
    disabled: (cfg) => cfg.llm.provider === 'anthropic' && !cfg.advanced.developerMode,
    hint: 'Local containers typically use http://localhost:11434 (Ollama) or http://localhost:8080/v1 (llama.cpp, vLLM, LM Studio).',
    synonyms: 'endpoint server address connection',
  }),
  model('model', {
    id: 64,
    group: 'Provider',
    label: 'Model',
    kind: 'model',
    visible: notMock,
    maxLength: 200,
  }),
  model('mockReplySpeed', {
    id: 76,
    group: 'Provider',
    label: 'Mock reply speed',
    kind: 'range',
    min: 1,
    max: 1000,
    suffix: 'chars/sec',
    visible: (cfg) => cfg.llm.provider === 'mock',
  }),
  model('timeoutMs', {
    id: 65,
    group: 'Provider',
    label: 'Request timeout',
    kind: 'number',
    min: 5,
    max: 600,
    multiplier: 1000,
    suffix: 's',
    visible: notMock,
  }),
  model('retryAttempts', {
    id: 66,
    group: 'Provider',
    label: 'Retry attempts',
    kind: 'select',
    options: OPTIONS.retryAttempts,
    visible: notMock,
    hint: 'Connection-reset retries are limited to one before the first token. Higher selections currently use that limit.',
  }),
  model('systemPrompt', {
    id: 67,
    group: 'Generation',
    label: 'System prompt',
    kind: 'textarea',
    rows: 6,
    maxLength: 8000,
    synonyms: 'instructions personality',
  }),
  model('promptPreset', {
    id: 68,
    group: 'Generation',
    label: 'Prompt preset',
    kind: 'select',
    options: OPTIONS.promptPreset,
  }),
  model('temperature', {
    id: 69,
    group: 'Generation',
    label: 'Temperature',
    kind: 'range',
    min: 0,
    max: 2,
    step: 0.05,
  }),
  model('topP', {
    id: 70,
    group: 'Generation',
    label: 'Top P',
    kind: 'range',
    min: 0,
    max: 1,
    step: 0.01,
  }),
  model('maxTokens', {
    id: 71,
    group: 'Generation',
    label: 'Max response tokens',
    kind: 'number',
    min: 64,
    max: 32768,
  }),
  model('stopSequences', {
    id: 72,
    group: 'Generation',
    label: 'Stop sequences',
    kind: 'tags',
    hint: 'Up to four sequences; press Enter to add.',
  }),
  model('stream', {
    id: 73,
    group: 'Generation',
    label: 'Stream responses',
    kind: 'toggle',
    hint: 'Turning this off disables the typewriter effect and delays all speech until the full reply arrives.',
  }),
  model('contextMode', {
    id: 74,
    group: 'Conversation Memory',
    label: 'Context to send',
    kind: 'select',
    options: OPTIONS.contextMode,
  }),
  model('tokenBudget', {
    id: 75,
    group: 'Conversation Memory',
    label: 'Token budget',
    kind: 'number',
    min: 512,
    max: 200000,
    visible: (cfg) => cfg.llm.contextMode === 'token-budget',
  }),
  model('persistence', {
    id: 76,
    group: 'Conversation Memory',
    label: 'Save conversations to disk',
    kind: 'select',
    options: OPTIONS.persistence,
  }),
  model('enableImages', {
    id: 78,
    group: 'Image & Attachment Handling',
    label: 'Enable image attachments',
    kind: 'toggle',
  }),
  model('imageDetail', {
    id: 79,
    group: 'Image & Attachment Handling',
    label: 'Image detail level',
    kind: 'select',
    options: OPTIONS.imageDetail,
    visible: (cfg) => cfg.llm.enableImages,
  }),
  model('maxImageDim', {
    id: 80,
    group: 'Image & Attachment Handling',
    label: 'Max image dimension',
    kind: 'select',
    options: OPTIONS.maxImageDim,
    visible: (cfg) => cfg.llm.enableImages,
  }),
  model('reencodeFormat', {
    id: 81,
    group: 'Image & Attachment Handling',
    label: 'Re-encode format',
    kind: 'select',
    options: OPTIONS.reencodeFormat,
    visible: (cfg) => cfg.llm.enableImages,
  }),
  model('maxAttachments', {
    id: 82,
    group: 'Image & Attachment Handling',
    label: 'Max attachments per message',
    kind: 'number',
    min: 1,
    max: 10,
    visible: (cfg) => cfg.llm.enableImages,
  }),
  bubble('scale', {
    id: 118,
    group: 'Chat Bubble — Size & Position',
    label: 'Bubble scale',
    kind: 'range',
    min: 50,
    max: 250,
    step: 5,
    multiplier: 0.01,
    suffix: '%',
    synonyms: 'zoom resize size',
  }),
  bubble('scaleRelativeTo', {
    id: 119,
    group: 'Chat Bubble — Size & Position',
    label: 'Scale is relative to',
    kind: 'select',
    options: OPTIONS.scaleRelativeTo,
  }),
  bubble('maxWidthPx', {
    id: 120,
    group: 'Chat Bubble — Size & Position',
    label: 'Maximum width',
    kind: 'number',
    min: 160,
    max: 1200,
    suffix: 'px',
    visible: (cfg) => cfg.bubble.scaleRelativeTo !== 'screen',
  }),
  bubble('maxHeightPx', {
    id: 121,
    group: 'Chat Bubble — Size & Position',
    label: 'Maximum height',
    kind: 'number',
    min: 80,
    max: 1000,
    suffix: 'px',
    visible: (cfg) => cfg.bubble.scaleRelativeTo !== 'screen',
  }),
  bubble('bubblePlacement', {
    id: 122,
    group: 'Chat Bubble — Size & Position',
    label: 'Bubble placement',
    kind: 'select',
    options: OPTIONS.bubblePlacement,
  }),
  bubble('gapFromSpritePx', {
    id: 123,
    group: 'Chat Bubble — Size & Position',
    label: 'Gap from sprite',
    kind: 'range',
    min: 0,
    max: 80,
    suffix: 'px',
  }),
  bubble('showTail', {
    id: 124,
    group: 'Chat Bubble — Size & Position',
    label: 'Show bubble tail',
    kind: 'toggle',
  }),
  bubble('maxWidthPct', {
    id: 125,
    group: 'Chat Bubble — Size & Position',
    label: 'Max width (% of screen)',
    kind: 'range',
    min: 10,
    max: 60,
    multiplier: 0.01,
    suffix: '%',
    visible: (cfg) => cfg.bubble.scaleRelativeTo === 'screen',
  }),
  bubble('maxHeightPct', {
    id: 126,
    group: 'Chat Bubble — Size & Position',
    label: 'Max height (% of screen)',
    kind: 'range',
    min: 10,
    max: 80,
    multiplier: 0.01,
    suffix: '%',
    visible: (cfg) => cfg.bubble.scaleRelativeTo === 'screen',
  }),
  bubble('scrollbar', {
    id: 127,
    group: 'Chat Bubble — Scrolling',
    label: 'Scrollbar',
    kind: 'select',
    options: OPTIONS.scrollbar,
  }),
  bubble('autoScroll', {
    id: 128,
    group: 'Chat Bubble — Scrolling',
    label: 'Auto-scroll to newest text',
    kind: 'toggle',
  }),
  bubble('wheelBehavior', {
    id: 129,
    group: 'Chat Bubble — Scrolling',
    label: 'Mouse wheel over bubble',
    kind: 'select',
    options: OPTIONS.wheelBehavior,
  }),
  bubble('theme', {
    id: 130,
    group: 'Chat Bubble — Style',
    label: 'Theme',
    kind: 'select',
    options: OPTIONS.theme,
  }),
  bubble('backgroundColor', {
    id: 131,
    group: 'Chat Bubble — Style',
    label: 'Background color',
    kind: 'color',
    visible: (cfg) => cfg.bubble.theme === 'custom',
  }),
  bubble('textColor', {
    id: 132,
    group: 'Chat Bubble — Style',
    label: 'Text color',
    kind: 'color',
    visible: (cfg) => cfg.bubble.theme === 'custom',
  }),
  bubble('accentColor', {
    id: 133,
    group: 'Chat Bubble — Style',
    label: 'Accent color',
    kind: 'color',
    visible: (cfg) => cfg.bubble.theme === 'custom',
  }),
  bubble('backgroundOpacity', {
    id: 134,
    group: 'Chat Bubble — Style',
    label: 'Background opacity',
    kind: 'range',
    min: 20,
    max: 100,
    multiplier: 0.01,
    suffix: '%',
  }),
  bubble('backdropBlur', {
    id: 135,
    group: 'Chat Bubble — Style',
    label: 'Background blur',
    kind: 'select',
    options: OPTIONS.backdropBlur,
    hint: 'Strong Acrylic is unavailable in this build.',
  }),
  bubble('cornerRadiusPx', {
    id: 136,
    group: 'Chat Bubble — Style',
    label: 'Corner radius',
    kind: 'range',
    min: 0,
    max: 32,
    suffix: 'px',
  }),
  bubble('paddingPx', {
    id: 137,
    group: 'Chat Bubble — Style',
    label: 'Padding',
    kind: 'range',
    min: 4,
    max: 32,
    suffix: 'px',
  }),
  bubble('border', {
    id: 138,
    group: 'Chat Bubble — Style',
    label: 'Border',
    kind: 'select',
    options: OPTIONS.border,
  }),
  bubble('shadow', {
    id: 139,
    group: 'Chat Bubble — Style',
    label: 'Drop shadow',
    kind: 'select',
    options: OPTIONS.shadow,
  }),
  bubble('fontFamily', {
    id: 140,
    group: 'Chat Bubble — Text',
    label: 'Font',
    kind: 'font',
    hint: 'Suggested Windows fonts and bundled Figma fonts. You can enter another installed family name.',
  }),
  bubble('fontSizePx', {
    id: 141,
    group: 'Chat Bubble — Text',
    label: 'Font size',
    kind: 'range',
    min: 10,
    max: 28,
    suffix: 'px',
  }),
  bubble('lineHeight', {
    id: 142,
    group: 'Chat Bubble — Text',
    label: 'Line height',
    kind: 'range',
    min: 1,
    max: 2.2,
    step: 0.05,
  }),
  bubble('renderMarkdown', {
    id: 143,
    group: 'Chat Bubble — Text',
    label: 'Render Markdown',
    kind: 'toggle',
  }),
  bubble('codeTheme', {
    id: 144,
    group: 'Chat Bubble — Text',
    label: 'Code block theme',
    kind: 'select',
    options: OPTIONS.codeTheme,
    visible: (cfg) => cfg.bubble.renderMarkdown,
  }),
  bubble('textReveal', {
    id: 145,
    group: 'Chat Bubble — Text',
    label: 'Text reveal',
    kind: 'select',
    options: OPTIONS.textReveal,
  }),
  bubble('revealRate', {
    id: 146,
    group: 'Chat Bubble — Text',
    label: 'Reveal speed',
    kind: 'range',
    min: 10,
    max: 200,
    suffix: 'units/sec',
    visible: (cfg) => cfg.bubble.textReveal !== 'instant',
    disabled: (cfg) => speech(cfg) && cfg.bubble.matchRevealToSpeech,
    disabledHint: 'Reveal speed is being matched to the voice.',
  }),
  bubble('matchRevealToSpeech', {
    id: 147,
    group: 'Chat Bubble — Text',
    label: 'Match reveal speed to speech',
    kind: 'toggle',
    visible: speech,
  }),
  bubble('dwellMs', {
    id: 148,
    group: 'Bubble Lifetime',
    label: 'Hide the bubble',
    kind: 'select',
    options: [
      ['0', 'Only when I dismiss it'],
      ['10000', 'After 10 seconds'],
      ['20000', 'After 20 seconds'],
      ['30000', 'After 30 seconds'],
      ['60000', 'After 60 seconds'],
    ],
  }),
  bubble('keepOpenOnHover', {
    id: 149,
    group: 'Bubble Lifetime',
    label: 'Keep open while the mouse is over it',
    kind: 'toggle',
    visible: (cfg) => cfg.bubble.dwellMs !== 0,
  }),
  bubble('waitForSpeech', {
    id: 150,
    group: 'Bubble Lifetime',
    label: 'Wait for speech to finish before hiding',
    kind: 'toggle',
    visible: speech,
  }),
  input('openOn', {
    id: 151,
    group: 'Input Box',
    label: 'Open the input box on',
    kind: 'select',
    options: OPTIONS.openOn,
  }),
  input('sendWith', {
    id: 152,
    group: 'Input Box',
    label: 'Send message with',
    kind: 'select',
    options: OPTIONS.sendWith,
  }),
  input('width', {
    id: 153,
    group: 'Input Box',
    label: 'Input box width',
    kind: 'select',
    options: OPTIONS.inputWidth,
  }),
  input('keepOpenAfterSend', {
    id: 154,
    group: 'Input Box',
    label: 'Keep the input box open after sending',
    kind: 'toggle',
  }),
  input('rememberDraft', {
    id: 155,
    group: 'Input Box',
    label: 'Remember draft text',
    kind: 'toggle',
  }),
];
export const spriteSetting = (
  target: string,
  key: string,
  definition: Omit<Setting, 'section' | 'key' | 'panel' | 'group'>,
): Setting => ({
  ...definition,
  panel: 'Sprites',
  group: target,
  section: 'sprite',
  key: target + '.' + key,
});
export const SPRITE_SEARCH_LABELS = [
  'Idle Thinking Speaking source type file folder browse frame width height count columns frame order playback speed fps playback mode timing anchor point custom anchor preview scrubber reset default sprite',
  'Mouth frames lip sync driven by audio amplitude text streaming rate fixed loop file folder frame count quietest loudest offset sensitivity smoothing silence threshold Test Mouth Sync',
  'Import Sprite Pack Export Sprite Pack Open Sprites Folder',
];
export function matchesSearch(label: string, query: string) {
  const haystack = label.toLocaleLowerCase();
  return query
    .toLocaleLowerCase()
    .trim()
    .split(/\s+/)
    .every((word) => {
      if (haystack.includes(word)) return true;
      let at = 0;
      for (const char of haystack) if (char === word[at]) at++;
      return at === word.length;
    });
}
