/** Persisted values and exact Settings labels, maintained independently of Figma text. */
export const OPTIONS = {
  spriteMode: [
    ['static', 'Static image'],
    ['sheet', 'Sprite sheet'],
    ['frames', 'Image sequence (folder)'],
  ],
  playbackMode: [
    ['loop', 'Loop forever'],
    ['once-hold', 'Play once, hold last frame'],
    ['once-idle', 'Play once, return to idle'],
    ['ping-pong', 'Ping-pong (loop back and forth)'],
  ],
  frameOrder: [
    ['row-major', 'Left to right, then down'],
    ['column-major', 'Top to bottom, then across'],
  ],
  anchor: [
    ['bottom-center', 'Bottom center'],
    ['center', 'Center'],
    ['top-center', 'Top center'],
    ['bottom-left', 'Bottom left'],
    ['bottom-right', 'Bottom right'],
    ['custom', 'Custom…'],
  ],
  gifTimingSource: [
    ['file', "Use the file's own frame delays"],
    ['override', 'Override with fixed fps'],
  ],
  scaleMode: [
    ['fixed', 'Fixed percentage'],
    ['dpi-aware', 'Match display scaling (DPI aware)'],
  ],
  pixelated: [
    ['auto', 'Automatic (detect pixel art)'],
    ['off', 'Always smooth (bilinear)'],
    ['on', 'Never smooth (nearest neighbor)'],
  ],
  transition: [
    ['cut', 'Instant cut'],
    ['crossfade', 'Crossfade'],
  ],
  mouthDriver: [
    ['amplitude', 'Audio amplitude'],
    ['text-rate', 'Text streaming rate'],
    ['fixed-loop', 'Fixed loop'],
  ],
  mouthMode: [
    ['sheet', 'Sprite sheet'],
    ['frames', 'Image sequence (folder)'],
  ],
  listeningBehavior: [
    ['use-idle', 'Use idle'],
    ['use-thinking', 'Use thinking'],
    ['custom', 'Custom'],
  ],
  onClose: [
    ['tray', 'Minimize to tray'],
    ['quit', 'Quit the application'],
  ],
  fullscreenBehavior: [
    ['never', 'Never hide'],
    ['fullscreen', 'Hide for fullscreen apps'],
    ['fullscreen-and-games', 'Hide for fullscreen and exclusive-fullscreen games'],
  ],
  defaultAnchor: [
    ['tl', 'Top left'],
    ['tc', 'Top center'],
    ['tr', 'Top right'],
    ['ml', 'Middle left'],
    ['c', 'Center'],
    ['mr', 'Middle right'],
    ['bl', 'Bottom left'],
    ['bc', 'Bottom center'],
    ['br', 'Bottom right'],
  ],
  displayTarget: [
    ['cursor', 'Follow the cursor'],
    ['primary', 'Primary display'],
  ],
  updateChannel: [
    ['stable', 'Stable'],
    ['beta', 'Beta'],
    ['disabled', 'Disabled'],
  ],
  updateInstall: [
    ['auto', 'Download and install automatically'],
    ['notify', 'Notify me, let me choose'],
    ['check-only', 'Check only, never download'],
  ],
  llmProvider: [
    ['openai-compatible', 'OpenAI-compatible'],
    ['anthropic', 'Anthropic'],
    ['ollama', 'Ollama'],
    ['mock', 'Mock (testing)'],
  ],
  retryAttempts: [
    ['0', 'None'],
    ['1', '1 retry'],
    ['2', '2 retries'],
    ['3', '3 retries'],
  ],
  promptPreset: [
    ['custom', 'Custom'],
    ['helpful-companion', 'Helpful companion'],
    ['persona-driven', 'Persona-driven'],
    ['concise-assistant', 'Concise assistant'],
    ['playful-character', 'Playful character'],
    ['technical-expert', 'Technical expert'],
    ['silent-observer', 'Silent observer'],
  ],
  contextMode: [
    ['none', 'No history (single turn)'],
    ['last5', 'Last 5 exchanges'],
    ['last10', 'Last 10 exchanges'],
    ['last25', 'Last 25 exchanges'],
    ['session', 'Entire session'],
    ['token-budget', 'Fit to token budget'],
  ],
  persistence: [
    ['never', 'Never save'],
    ['session', 'Keep for this session only'],
    ['permanent', 'Save permanently'],
  ],
  imageDetail: [
    ['auto', 'Automatic'],
    ['low', 'Low (cheaper, faster)'],
    ['high', 'High (more accurate)'],
  ],
  maxImageDim: [
    ['512', '512 px'],
    ['1024', '1024 px'],
    ['1536', '1536 px'],
    ['2048', '2048 px'],
    ['none', 'Do not resize'],
  ],
  reencodeFormat: [
    ['original', 'Keep original'],
    ['png', 'PNG'],
    ['jpeg', 'JPEG (quality 85)'],
    ['webp', 'WebP (quality 85)'],
  ],
  ttsProvider: [
    ['none', 'Off (text only)'],
    ['windows-sapi', 'Windows built-in (SAPI)'],
    ['openai-compatible-tts', 'OpenAI-compatible endpoint'],
    ['elevenlabs', 'ElevenLabs'],
    ['custom-http', 'Custom HTTP endpoint'],
  ],
  audioFormat: [
    ['mp3', 'MP3'],
    ['opus', 'Opus'],
    ['aac', 'AAC'],
    ['flac', 'FLAC'],
    ['wav', 'WAV'],
    ['pcm16', 'PCM'],
  ],
  customAudioFormat: [
    ['mp3', 'MP3'],
    ['wav', 'WAV'],
    ['opus', 'Opus'],
    ['ogg', 'OGG'],
    ['pcm16', 'PCM 16-bit 24kHz'],
  ],
  elevenModel: [
    ['eleven_flash_v2_5', 'Flash v2.5 (fastest, cheapest)'],
    ['eleven_turbo_v2_5', 'Turbo v2.5'],
    ['eleven_multilingual_v2', 'Multilingual v2 (highest quality)'],
  ],
  ttsMethod: [
    ['POST', 'POST'],
    ['GET', 'GET'],
  ],
  responseMode: [
    ['binary', 'Raw audio bytes'],
    ['json-base64', 'Base64 string in JSON field'],
    ['json-url', 'URL in JSON field'],
  ],
  beginSpeaking: [
    ['first-sentence', 'As soon as the first sentence is ready'],
    ['full-reply', 'After the full reply arrives'],
  ],
  onNewMessage: [
    ['stop', 'Stop speaking immediately'],
    ['finish-sentence', 'Finish the current sentence, then stop'],
    ['queue', 'Queue the new reply'],
  ],
  codeBlockSpeech: [
    ['skip', 'Skip silently'],
    ['announce', 'Say "code block"'],
    ['read', 'Read the code aloud'],
  ],
  linkSpeech: [
    ['label', 'Read the link text only'],
    ['full-url', 'Read the full URL'],
    ['skip', 'Skip links'],
  ],
  emojiSpeech: [
    ['skip', 'Skip'],
    ['describe', 'Read the description'],
  ],
  ttsFailure: [
    ['text-only', 'Fall back to text only'],
    ['sapi', 'Fall back to Windows SAPI'],
    ['notify', 'Show an error notification'],
  ],
  sttProvider: [
    ['none', 'Off (typing only)'],
    ['windows-dictation', 'Windows built-in dictation'],
    ['openai-compatible-stt', 'OpenAI-compatible endpoint (Whisper)'],
    ['whisper-local', 'Local Whisper executable'],
    ['custom-http', 'Custom HTTP endpoint'],
    ['mock', 'Mock (testing)'],
  ],
  outputMode: [
    ['json', 'JSON (--output-json)'],
    ['txt', 'Plain text (stdout)'],
  ],
  sttMethod: [
    ['POST', 'POST'],
    ['PUT', 'PUT'],
  ],
  uploadMode: [
    ['multipart-file', 'Multipart form file'],
    ['raw-body', 'Raw request body'],
    ['json-base64', 'Base64 string in JSON'],
  ],
  sttAudioFormat: [
    ['wav16', 'WAV 16-bit 16 kHz'],
    ['wav48', 'WAV 16-bit 48 kHz'],
    ['flac', 'FLAC'],
    ['opus', 'Opus (OGG)'],
    ['mp3', 'MP3'],
  ],
  activation: [
    ['push-to-talk', 'Push-to-talk (hold the hotkey)'],
    ['toggle', 'Toggle (press to start, press to stop)'],
    ['hands-free', 'Hands-free (stops when you stop talking)'],
  ],
  noiseSuppression: [
    ['default', 'Browser default'],
    ['aggressive', 'Aggressive'],
    ['off', 'Off'],
  ],
  transcriptAction: [
    ['hold', 'Put it in the input box and wait'],
    ['send', 'Send it immediately'],
    ['countdown', 'Send after a short countdown'],
  ],
  insertMode: [
    ['caret', 'At the cursor'],
    ['replace', 'Replace everything in the box'],
    ['append', 'Append to the end'],
  ],
  sttFailure: [
    ['error', 'Show an error and keep what I typed'],
    ['sapi-dictation', 'Fall back to Windows dictation'],
    ['discard', 'Silently discard'],
  ],
  scaleRelativeTo: [
    ['sprite', "The sprite's size"],
    ['pixels', 'A fixed pixel size'],
    ['screen', 'The screen size'],
  ],
  bubblePlacement: [
    ['auto', 'Automatic (avoid screen edges)'],
    ['above', 'Above the sprite'],
    ['below', 'Below the sprite'],
    ['left', 'Left of the sprite'],
    ['right', 'Right of the sprite'],
  ],
  scrollbar: [
    ['auto', 'Show while scrolling'],
    ['always', 'Always show'],
    ['never', 'Never show'],
  ],
  wheelBehavior: [
    ['scroll', 'Scrolls the bubble'],
    ['passthrough', 'Passes through to the window behind'],
  ],
  theme: [
    ['system', 'Follow Windows'],
    ['light', 'Light'],
    ['dark', 'Dark'],
    ['high-contrast', 'High contrast'],
    ['custom', 'Custom'],
  ],
  backdropBlur: [
    ['none', 'None'],
    ['subtle', 'Subtle'],
    ['acrylic', 'Strong (acrylic)'],
  ],
  border: [
    ['none', 'None'],
    ['thin', 'Thin'],
    ['thick', 'Thick'],
  ],
  shadow: [
    ['none', 'None'],
    ['soft', 'Soft'],
    ['strong', 'Strong'],
  ],
  codeTheme: [
    ['match', 'Match bubble theme'],
    ['github-light', 'GitHub Light'],
    ['github-dark', 'GitHub Dark'],
    ['monokai', 'Monokai'],
    ['solarized-dark', 'Solarized Dark'],
  ],
  textReveal: [
    ['instant', 'Appear instantly'],
    ['char', 'Typewriter by character'],
    ['word', 'Typewriter by word'],
  ],
  dwellMs: [
    ['0', 'Only when I dismiss it'],
    ['10000', 'After 10 seconds'],
    ['20000', 'After 20 seconds'],
    ['30000', 'After 30 seconds'],
    ['60000', 'After 60 seconds'],
  ],
  openOn: [
    ['single-click', 'Single click'],
    ['double-click', 'Double click'],
    ['hotkey-only', 'Hotkey only'],
  ],
  sendWith: [
    ['enter', 'Enter'],
    ['ctrl-enter', 'Ctrl + Enter'],
  ],
  inputWidth: [
    ['match-bubble', 'Match the bubble width'],
    ['compact', 'Compact'],
    ['wide', 'Wide'],
  ],
  clickThrough: [
    ['alpha-mask', 'Per-pixel (alpha mask)'],
    ['bounding-box', 'Bounding box only'],
    ['never', 'Never click through'],
  ],
  hitTestEveryNFrames: [
    ['1', 'Every frame'],
    ['2', 'Every 2nd frame'],
    ['4', 'Every 4th frame'],
  ],
  dragModifier: [
    ['none', 'No modifier'],
    ['alt', 'Hold Alt'],
    ['ctrl', 'Hold Ctrl'],
    ['shift', 'Hold Shift'],
  ],
  fpsCap: [
    ['display', 'Match display refresh rate'],
    ['60', '60 fps'],
    ['30', '30 fps'],
    ['15', '15 fps (battery saver)'],
  ],
  spriteCacheMb: [
    ['64', '64 MB'],
    ['128', '128 MB'],
    ['256', '256 MB'],
    ['512', '512 MB'],
  ],
  proxyMode: [
    ['system', 'Use Windows system proxy'],
    ['direct', 'No proxy (direct)'],
    ['manual', 'Manual configuration'],
  ],
  logLevel: [
    ['error', 'Errors only'],
    ['warn', 'Warnings'],
    ['info', 'Info'],
    ['debug', 'Debug'],
    ['trace', 'Trace (verbose)'],
  ],
  forceState: [
    ['auto', 'Automatic'],
    ['idle', 'Idle'],
    ['thinking', 'Thinking'],
    ['speaking', 'Speaking'],
    ['listening', 'Listening'],
  ],
  pronouns: [
    ['', 'Not specified'],
    ['she/her', 'she/her'],
    ['it/its', 'it/its'],
    ['he/him', 'he/him'],
    ['they/them', 'they/them'],
    ['custom', 'Custom…'],
  ],
  injection: [
    ['after', 'After my system prompt'],
    ['replace', 'Replace my system prompt'],
    ['before', 'Before my system prompt'],
  ],
  replyLength: [
    ['none', 'Follow my system prompt'],
    ['one-two', 'One or two sentences'],
    ['paragraph', 'A short paragraph'],
    ['unbounded', 'No limit'],
  ],
  characterBreak: [
    ['always', 'Always stay in character'],
    ['technical', 'Drop character for technical answers'],
    ['none', 'No instruction'],
  ],
  greetingMode: [
    ['off', "Don't greet me"],
    ['static', 'Show a fixed message'],
    ['generated', 'Ask the model for a greeting'],
  ],
  greetingFrequency: [
    ['per-launch', 'Once per launch'],
    ['per-show', 'Every time the sprite appears'],
    ['daily', 'Once a day'],
  ],
  packPersonaPolicy: [
    ['ask', 'Ask me before applying'],
    ['auto', 'Apply automatically'],
    ['ignore', 'Always ignore them'],
  ],
  onSwitch: [
    ['new-conversation', 'Start a new conversation'],
    ['keep', 'Keep the current conversation'],
    ['ask', 'Ask me each time'],
  ],
} as const;
export const SPRITE_STATES = ['idle', 'thinking', 'speaking', 'listening'] as const;
export const REQUIRED_SPRITE_STATES = ['idle', 'thinking', 'speaking'] as const;
export type SpriteState = (typeof SPRITE_STATES)[number];
