import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { defaults } from '../../src/shared/config';
import { StateController } from '../../src/main/services/stateController';
beforeEach(() => vi.useFakeTimers());
afterEach(() => vi.useRealTimers());
const setup = () => {
  const config = defaults(),
    hide = vi.fn(),
    emit = vi.fn();
  config.bubble.dwellMs = 10000;
  const state = new StateController(() => config, emit, hide);
  return { config, hide, emit, state };
};
it('fast output and completion respect minimum thinking, then dwell before idle', () => {
  const { state, hide } = setup();
  state.begin('a');
  state.output('a');
  state.complete('a');
  expect(state.snapshot.state).toBe('thinking');
  vi.advanceTimersByTime(249);
  expect(state.snapshot.state).toBe('thinking');
  vi.advanceTimersByTime(1);
  expect(state.snapshot.state).toBe('speaking');
  vi.advanceTimersByTime(9999);
  expect(state.snapshot.state).toBe('speaking');
  vi.advanceTimersByTime(1);
  expect(state.snapshot).toEqual({ state: 'idle', requestId: null });
  expect(hide).toHaveBeenCalledOnce();
});
it('first audio can release thinking; stream and queued audio gate dwell', () => {
  const { state, hide } = setup();
  state.begin('a');
  state.audio('a', false);
  vi.advanceTimersByTime(250);
  expect(state.snapshot.state).toBe('speaking');
  state.complete('a');
  vi.advanceTimersByTime(30000);
  expect(hide).not.toHaveBeenCalled();
  state.audio('a', true);
  vi.advanceTimersByTime(10000);
  expect(state.snapshot.state).toBe('idle');
  expect(hide).toHaveBeenCalledOnce();
});
it('waitForSpeech off allows bubble expiry during playback but keeps speaking', () => {
  const { state, config, hide } = setup();
  config.bubble.waitForSpeech = false;
  state.begin('a');
  state.output('a');
  state.audio('a', false);
  vi.advanceTimersByTime(250);
  state.complete('a');
  vi.advanceTimersByTime(10000);
  expect(hide).toHaveBeenCalledOnce();
  expect(state.snapshot.state).toBe('speaking');
  state.audio('a', true);
  expect(state.snapshot.state).toBe('idle');
});
it('hover holds speaking and preserves remaining dwell, with live hover toggle', () => {
  const { state, config } = setup();
  state.begin('a');
  vi.advanceTimersByTime(300);
  state.output('a');
  state.complete('a');
  vi.advanceTimersByTime(3000);
  state.hover(true);
  vi.advanceTimersByTime(60000);
  expect(state.snapshot.state).toBe('speaking');
  config.bubble.keepOpenOnHover = false;
  state.settingsChanged();
  vi.advanceTimersByTime(6999);
  expect(state.snapshot.state).toBe('speaking');
  vi.advanceTimersByTime(1);
  expect(state.snapshot.state).toBe('idle');
});
it('indefinite dwell holds until dismissal, cancellation is immediate even during minimum thinking', () => {
  const { state, config, hide } = setup();
  config.bubble.dwellMs = 0;
  state.begin('a');
  state.output('a');
  state.cancel('a');
  vi.advanceTimersByTime(250);
  expect(state.snapshot.state).toBe('idle');
  state.begin('b');
  state.output('b');
  state.complete('b');
  vi.advanceTimersByTime(1000000);
  expect(state.snapshot.state).toBe('speaking');
  expect(hide).not.toHaveBeenCalled();
  state.cancel();
  expect(state.snapshot.state).toBe('idle');
});
it('errors release immediately, retain the error bubble and expire it after hover', () => {
  const { state, hide } = setup();
  state.begin('a');
  state.output('a');
  state.fail('a');
  state.hover(true);
  vi.advanceTimersByTime(60000);
  expect(state.snapshot.state).toBe('idle');
  expect(hide).not.toHaveBeenCalled();
  state.hover(false);
  vi.advanceTimersByTime(10000);
  expect(hide).toHaveBeenCalledOnce();
});
it('superseded request output, audio, error and completion cannot change a new request', () => {
  const { state, hide } = setup();
  state.begin('a');
  state.output('a');
  state.begin('b');
  state.output('a');
  state.audio('a', false);
  state.complete('a');
  state.fail('a');
  state.cancel('a');
  vi.advanceTimersByTime(500);
  expect(state.snapshot).toEqual({ state: 'thinking', requestId: 'b' });
  state.output('b');
  expect(state.snapshot.state).toBe('speaking');
  vi.advanceTimersByTime(60000);
  expect(hide).not.toHaveBeenCalled();
});
it('listening, batch transcription, autosend, no-send and barge-in use the same lifecycle', () => {
  const { state } = setup();
  state.listen();
  expect(state.snapshot.state).toBe('listening');
  state.transcribing();
  expect(state.snapshot.state).toBe('thinking');
  state.transcript('a');
  state.output('a');
  vi.advanceTimersByTime(250);
  expect(state.snapshot.state).toBe('speaking');
  state.listen();
  expect(state.snapshot).toEqual({ state: 'listening', requestId: null });
  state.complete('a');
  vi.advanceTimersByTime(60000);
  expect(state.snapshot.state).toBe('listening');
  state.transcript(null);
  expect(state.snapshot.state).toBe('idle');
  state.listen();
  state.cancel();
  expect(state.snapshot.state).toBe('idle');
});
it('state overrides are session only and returning to auto reveals ongoing lifecycle', () => {
  const { state } = setup();
  state.force('listening');
  state.begin('a');
  state.output('a');
  vi.advanceTimersByTime(250);
  expect(state.snapshot.state).toBe('listening');
  state.force('auto');
  expect(state.snapshot.state).toBe('speaking');
});
it('empty completion expires without a speaking phase, and disposal cancels timers', () => {
  const { state, hide } = setup();
  state.begin('a');
  state.complete('a');
  expect(state.snapshot.state).toBe('idle');
  vi.advanceTimersByTime(10000);
  expect(hide).toHaveBeenCalledOnce();
  state.begin('b');
  state.output('b');
  state.dispose();
  vi.advanceTimersByTime(10000);
  expect(state.snapshot.state).toBe('thinking');
  expect(hide).toHaveBeenCalledOnce();
});
it('a cancelled partial reply expires while the sprite immediately becomes idle', () => {
  const { state, hide } = setup();
  state.begin('a');
  state.output('a');
  state.cancel('a', true);
  expect(state.snapshot.state).toBe('idle');
  vi.advanceTimersByTime(9999);
  expect(hide).not.toHaveBeenCalled();
  vi.advanceTimersByTime(1);
  expect(hide).toHaveBeenCalledOnce();
});
